### ISSUE TITLE
Method to cancel retried jobs

### ISSUE THREAD

**Issue by doits** [isaacseymour/activejob-retry#41]
Is there a method to cancel jobs that are scheduled because of a retry?

**Comment by isaacseymour** [comment]
Hi @doits, this really depends on your queue adapter - this gem just enqueues a new job with a delay, and the queue adapter may have some way of removing that from the queue.

**Comment by doits** [comment]
Thanks for the info. Is there some way to identify jobs put into the queue adapter? I could imagine to iterate over all enqueued jobs and check for some attribute or so.

In my case I use sidekiq, so I can iterate over all jobs with `Sidekiq::Queue.new.each`, but is there any way to identify a retried job?

**Comment by isaacseymour** [comment]
Yep, this gem adds a `retry_attempt` key to the serialised job, so you
could filter on the value of that when cancelling jobs. Sidekiq also has
it's own retry attempt counter though, so you'll need to be careful to pick
the right one...

**Comment by isaacseymour** [comment]
Just to clarify, for Sidekiq:

- `Sidekiq::Job#retry_count` is the Sidekiq retry count (which only increments when the ActiveJob::Retry retries run out)
- `Sidekiq::Job#args.first["retry_attempt"]` is the ActiveJob retry counter
