### ISSUE TITLE
Rails 5.1 support

### ISSUE THREAD

**Issue by Throne3d** [isaacseymour/activejob-retry#44]
Hi there! I haven't actually tested this gem, but as Rails doesn't seem to support retry functionality like this, I plan to use it.

I'm also planning on upgrading to Rails 5.1 shortly, though, and as it (Rails 5.1) was released back in April I was wondering if this gem supported it? It doesn't mention that it *does* on the README (whereas it does mention Rails 4.2 and 5.0, suggesting it doesn't), but it looks like this was last updated in February.

I suppose if it doesn't work on Rails 5.1, this is a request to add that, and if it does, this is a request to update the documentation to reflect that?

Thanks!

**Comment by isaacseymour** [comment]
Hey, I've been using this in production at work with rails 5.1 pretty much
since rails 5.1 was released, and it's been working fine. I'll update the
docs this weekend. Thanks for raising this!

**Comment by Throne3d** [comment]
Hm. I [attempted to do it myself](https://github.com/isaacseymour/activejob-retry/compare/master...Throne3d:add/support-rails-5.1) (and also revert 668076d4c4961d118ad817a25bb0c34caca05733 as it's no longer applicable), but:

1. The gemspec file complains about the use of `Date` (I fixed this by manually requiring it up the top)
2. Rubocop seems to be failing on files that previously passed; perhaps they added new cops since it was last run?
3. `bundle exec rake test` appears to be exiting with code 1 on some tests (for me, locally, there are two failures and two errors, as [here](https://travis-ci.org/Throne3d/activejob-retry/jobs/278751653#L2329))

Here's the relevant Travis: https://travis-ci.org/Throne3d/activejob-retry/builds/278751637

I think I'll just leave it up to you, since I'm not sure which of those you want to fix and which you want to ignore. It might also be worth testing against Ruby 2.4.1 instead of 2.4.0.

Thanks for the quick response, though!

**Comment by isaacseymour** [comment]
Okay, I've removed the integration specs (they were originally copy-pasted from the ActiveJob tests but haven't been updated in ages so probably aren't valuable anymore), and updated all the patch versions in the Travis spec. Now testing against Rails 4.2, 5.0, 5.1. Thanks for raising this :)

**Comment by Throne3d** [comment]
Thanks!
